name: Test React App
on: push
jobs:
  runs-on: ubuntu-latest
  steps:
    - name: Get repo code
      uses: actions/checkout@v3

    - name: install dependencies
      run: npm ci

    - name: Test app
      run: npm run test
